<?php

class user_pii_model extends model_logic
{
	private array $cols =
	[
		// Generated by the cli when creating the model file
		// Hand made for testing
		"user_pii_id" =>
		[
			"position"				=> "1",
			"data_type"				=> "int",	"column_type"		=> "int(11)",
			"column_key"			=> "PRI",	"extra"				=> "auto_increment",
			"default"				=> NULL,	"nullable"			=> FALSE,
			"char_max_length"		=> NULL,	"char_octet_length"	=> NULL,
			"datetime_precision"	=> NULL,	"numeric_precision"	=> 10,		"numeric_scale"	=> 0,
			"column_comment"		=> NULL
		],
		"user_pii_ulid" =>
		[
			"position"				=> "2",
			"data_type"				=> "char",	"column_type"		=> "char(26)",
			"column_key"			=> "",		"extra"				=> "",
			"default"				=> NULL,	"nullable"			=> FALSE,
			"char_max_length"		=> 26,		"char_octet_length"	=> 104,
			"datetime_precision"	=> NULL,	"numeric_precision"	=> NULL,	"numeric_scale"	=> 0,
			"column_comment"		=> NULL
		],
		"user_pii_active" =>
		[
			"position"				=> "3",
			"data_type"				=> "tinyint",				"column_type"		=> "tinyint(1)",
			"column_key"			=> "",						"extra"				=> "on update current_timestamp()",
			"default"				=> "current_timestamp()",	"nullable"			=> FALSE,
			"char_max_length"		=> NULL,					"char_octet_length"	=> NULL,
			"datetime_precision"	=> 0,						"numeric_precision"	=> 3,		"numeric_scale"	=> 0,
			"column_comment"		=> "If _archive or _del, _active = 0"
		],
		"user_pii_new" =>
		[
			"position"				=> "4",
			"data_type"				=> "datetime",	"column_type"		=> "datetime",
			"column_key"			=> "",			"extra"				=> "",
			"default"				=> NULL,		"nullable"			=> FALSE,
			"char_max_length"		=> NULL,		"char_octet_length"	=> NULL,
			"datetime_precision"	=> 0,			"numeric_precision"	=> NULL,	"numeric_scale"	=> 0,
			"column_comment"		=> NULL
		],
		"user_pii_edit" =>
		[
			"position"				=> "5",
			"data_type"				=> "timestamp",				"column_type"		=> "timestamp",
			"column_key"			=> "",						"extra"				=> "on update current_timestamp()",
			"default"				=> "current_timestamp()",	"nullable"			=> FALSE,
			"char_max_length"		=> NULL,					"char_octet_length"	=> NULL,
			"datetime_precision"	=> 0,						"numeric_precision"	=> NULL,	"numeric_scale"	=> NULL,
			"column_comment"		=> NULL
		],
		"user_pii_archive" =>
		[
			"position"				=> "6",
			"data_type"				=> "timestamp",	"column_type"		=> "timestamp",
			"column_key"			=> "",			"extra"				=> "",
			"default"				=> NULL,		"nullable"			=> TRUE,
			"char_max_length"		=> NULL,		"char_octet_length"	=> NULL,
			"datetime_precision"	=> 0,			"numeric_precision"	=> NULL,	"numeric_scale"	=> 0,
			"column_comment"		=> NULL
		],
		"user_pii_del" =>
		[
			"position"				=> "7",
			"data_type"				=> "timestamp",	"column_type"		=> "timestamp",
			"column_key"			=> "",			"extra"				=> "",
			"default"				=> NULL,		"nullable"			=> TRUE,
			"char_max_length"		=> NULL,		"char_octet_length"	=> NULL,
			"datetime_precision"	=> 0,			"numeric_precision"	=> NULL,	"numeric_scale"	=> 0,
			"column_comment"		=> NULL
		],
		"fk_user_id" =>
		[
			"position"				=> "8",
			"data_type"				=> "int",	"column_type"		=> "int(11)",
			"column_key"			=> "",		"extra"				=> "",
			"default"				=> NULL,	"nullable"			=> TRUE,
			"char_max_length"		=> NULL,	"char_octet_length"	=> NULL,
			"datetime_precision"	=> NULL,	"numeric_precision"	=> 10,		"numeric_scale"	=> 0,
			"column_comment"		=> NULL
		],
		"user_pii_email" =>
		[
			"position"				=> "9",
			"data_type"				=> "varchar",	"column_type"		=> "varchar(255)",
			"column_key"			=> "",			"extra"				=> "",
			"default"				=> NULL,		"nullable"			=> TRUE,
			"char_max_length"		=> 255,			"char_octet_length"	=> 1020,
			"datetime_precision"	=> NULL,		"numeric_precision"	=> NULL,	"numeric_scale"	=> NULL,
			"column_comment"		=> NULL
		],
		"user_pii_dob" =>
		[
			"position"				=> "10",
			"data_type"				=> "date",	"column_type"		=> "date",
			"column_key"			=> "",		"extra"				=> "",
			"default"				=> NULL,	"nullable"			=> TRUE,
			"char_max_length"		=> NULL,	"char_octet_length"	=> NULL,
			"datetime_precision"	=> NULL,	"numeric_precision"	=> NULL,	"numeric_scale"	=> NULL,
			"column_comment"		=> NULL
		],
		"user_pii_gender" =>
		[
			"position"				=> "11",
			"data_type"				=> "enum",	"column_type"		=> "enum('m','f','nb')",
			"column_key"			=> "",		"extra"				=> "",
			"default"				=> NULL,	"nullable"			=> TRUE,
			"char_max_length"		=> 2,		"char_octet_length"	=> 8,
			"datetime_precision"	=> NULL,	"numeric_precision"	=> NULL,	"numeric_scale"	=> NULL,
			"column_comment"		=> NULL
		],
	];

	public function __construct()
	{
		parent::__construct();
	}
}