<?php

class user_model extends model_logic
{
	private array $cols =
	[
		// Generated by the cli when creating the model file
		// Hand made for testing
		"user_id" =>
		[
			"position"				=> "1",
			"data_type"				=> "int",	"column_type"		=> "int(11)",
			"column_key"			=> "PRI",	"extra"				=> "auto_increment",
			"default"				=> NULL,	"nullable"			=> FALSE,
			"char_max_length"		=> NULL,	"char_octet_length"	=> NULL,
			"datetime_precision"	=> NULL,	"numeric_precision"	=> 10,		"numeric_scale"	=> 0,
			"column_comment"		=> NULL
		],
		"user_ulid" =>
		[
			"position"				=> "2",
			"data_type"				=> "char",	"column_type"		=> "char(26)",
			"column_key"			=> "",		"extra"				=> "",
			"default"				=> NULL,	"nullable"			=> TRUE,
			"char_max_length"		=> 26,		"char_octet_length"	=> 104,
			"datetime_precision"	=> NULL,	"numeric_precision"	=> NULL,	"numeric_scale"	=> 0,
			"column_comment"		=> NULL
		],
		"user_active" =>
		[
			"position"				=> "3",
			"data_type"				=> "tinyint",				"column_type"		=> "tinyint(1)",
			"column_key"			=> "",						"extra"				=> "on update current_timestamp()",
			"default"				=> "current_timestamp()",	"nullable"			=> FALSE,
			"char_max_length"		=> NULL,					"char_octet_length"	=> NULL,
			"datetime_precision"	=> 0,						"numeric_precision"	=> 3,		"numeric_scale"	=> 0,
			"column_comment"		=> "If _archive or _del, _active = 0"
		],
		"user_new" =>
		[
			"position"				=> "4",
			"data_type"				=> "datetime",	"column_type"		=> "datetime",
			"column_key"			=> "",			"extra"				=> "",
			"default"				=> NULL,		"nullable"			=> FALSE,
			"char_max_length"		=> NULL,		"char_octet_length"	=> NULL,
			"datetime_precision"	=> 0,			"numeric_precision"	=> NULL,	"numeric_scale"	=> 0,
			"column_comment"		=> NULL
		],
		"user_edit" =>
		[
			"position"				=> "5",
			"data_type"				=> "timestamp",				"column_type"		=> "timestamp",
			"column_key"			=> "",						"extra"				=> "on update current_timestamp()",
			"default"				=> "current_timestamp()",	"nullable"			=> FALSE,
			"char_max_length"		=> NULL,					"char_octet_length"	=> NULL,
			"datetime_precision"	=> 0,						"numeric_precision"	=> NULL,	"numeric_scale"	=> NULL,
			"column_comment"		=> NULL
		],
		"user_archive" =>
		[
			"position"				=> "6",
			"data_type"				=> "timestamp",	"column_type"		=> "timestamp",
			"column_key"			=> "",			"extra"				=> "",
			"default"				=> NULL,		"nullable"			=> TRUE,
			"char_max_length"		=> NULL,		"char_octet_length"	=> NULL,
			"datetime_precision"	=> 0,			"numeric_precision"	=> NULL,	"numeric_scale"	=> 0,
			"column_comment"		=> NULL
		],
		"user_del" =>
		[
			"position"				=> "7",
			"data_type"				=> "timestamp",	"column_type"		=> "timestamp",
			"column_key"			=> "",			"extra"				=> "",
			"default"				=> NULL,		"nullable"			=> TRUE,
			"char_max_length"		=> NULL,		"char_octet_length"	=> NULL,
			"datetime_precision"	=> 0,			"numeric_precision"	=> NULL,	"numeric_scale"	=> 0,
			"column_comment"		=> NULL
		],
		"user_first_name" =>
		[
			"position"				=> "8",
			"data_type"				=> "char",	"column_type"		=> "char(25)",
			"column_key"			=> "",		"extra"				=> "",
			"default"				=> NULL,	"nullable"			=> TRUE,
			"char_max_length"		=> 25,		"char_octet_length"	=> 100,
			"datetime_precision"	=> NULL,	"numeric_precision"	=> NULL,	"numeric_scale"	=> 0,
			"column_comment"		=> NULL
		],
		"user_middle_name" =>
		[
			"position"				=> "9",
			"data_type"				=> "char",	"column_type"		=> "char(25)",
			"column_key"			=> "",		"extra"				=> "",
			"default"				=> NULL,	"nullable"			=> TRUE,
			"char_max_length"		=> 25,		"char_octet_length"	=> 100,
			"datetime_precision"	=> NULL,	"numeric_precision"	=> NULL,	"numeric_scale"	=> 0,
			"column_comment"		=> NULL
		],
		"user_family_name" =>
		[
			"position"				=> "10",
			"data_type"				=> "char",	"column_type"		=> "char(25)",
			"column_key"			=> "",		"extra"				=> "",
			"default"				=> NULL,	"nullable"			=> TRUE,
			"char_max_length"		=> 25,		"char_octet_length"	=> 100,
			"datetime_precision"	=> NULL,	"numeric_precision"	=> NULL,	"numeric_scale"	=> 0,
			"column_comment"		=> NULL
		],
		"user_full_name" =>
		[
			"position"				=> "11",
			"data_type"				=> "char",	"column_type"		=> "char(80)",
			"column_key"			=> "",		"extra"				=> "",
			"default"				=> NULL,	"nullable"			=> TRUE,
			"char_max_length"		=> 80,		"char_octet_length"	=> 640,
			"datetime_precision"	=> NULL,	"numeric_precision"	=> NULL,	"numeric_scale"	=> 0,
			"column_comment"		=> NULL
		],
		"user_first_name_sound" =>
		[
			"position"				=> "12",
			"data_type"				=> "char",	"column_type"		=> "char(80)",
			"column_key"			=> "",		"extra"				=> "",
			"default"				=> NULL,	"nullable"			=> TRUE,
			"char_max_length"		=> 80,		"char_octet_length"	=> 640,
			"datetime_precision"	=> NULL,	"numeric_precision"	=> NULL,	"numeric_scale"	=> 0,
			"column_comment"		=> NULL
		],
		"user_middle_name_sound" =>
		[
			"position"				=> "13",
			"data_type"				=> "char",	"column_type"		=> "char(80)",
			"column_key"			=> "",		"extra"				=> "",
			"default"				=> NULL,	"nullable"			=> TRUE,
			"char_max_length"		=> 80,		"char_octet_length"	=> 640,
			"datetime_precision"	=> NULL,	"numeric_precision"	=> NULL,	"numeric_scale"	=> 0,
			"column_comment"		=> NULL
		],
	];

	public function __construct()
	{
		parent::__construct();
	}
}